# Generated by Django 5.0.6 on 2024-08-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CreateUser',
        ),
    ]
