# Generated by Django 5.0.6 on 2024-08-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0002_rename_user_createuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearOrden',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=2)),
                ('solicitada_por', models.CharField(max_length=15)),
                ('tipo_orden', models.CharField(max_length=3)),
                ('tipo_carga', models.CharField(max_length=3)),
                ('tipo_contenido', models.CharField(max_length=3)),
                ('servicio', models.CharField(max_length=4)),
                ('equipo_adicional', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
            ],
        ),
    ]
