# Generated by Django 5.0.6 on 2024-08-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0003_crearorden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearOrden',
            new_name='CreateOrder',
        ),
    ]
