# Generated by Django 5.0.6 on 2024-08-20 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0004_rename_crearorden_createorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createorder',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='createorder',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='createorder',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='createorder',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='createorder',
            name='ruta',
            field=models.CharField(default='RL', max_length=2),
        ),
        migrations.AddField(
            model_name='createorder',
            name='sucursal_rol',
            field=models.CharField(default='JZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='equipo_adicional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='servicio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='solicitada_por',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='sucursal',
            field=models.CharField(default='JZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='tipo_carga',
            field=models.CharField(default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='tipo_contenido',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='tipo_orden',
            field=models.CharField(default='NAL', max_length=3),
        ),
    ]
