# Generated by Django 5.0.6 on 2024-08-20 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0006_createorder_fecha_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
