# Generated by Django 5.0.6 on 2024-08-20 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0008_createorder_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='fecha_previo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
