# Generated by Django 5.0.6 on 2024-08-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0010_alter_createorder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClient',
            fields=[
                ('cliente_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='createorder',
            name='servicio',
            field=models.CharField(default='NORM', max_length=4),
        ),
        migrations.AddField(
            model_name='createorder',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estatus.createclient'),
        ),
    ]
