# Generated by Django 5.0.6 on 2024-08-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0011_createclient_alter_createorder_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createorder',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CreateUser',
        ),
        migrations.DeleteModel(
            name='CreateClient',
        ),
        migrations.DeleteModel(
            name='CreateOrder',
        ),
    ]
