# Generated by Django 5.0.6 on 2024-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0013_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('posicion', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
