# Generated by Django 5.0.6 on 2024-08-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0014_lugares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtrip',
            old_name='trailer',
            new_name='carro',
        ),
        migrations.RenameField(
            model_name='newtrip',
            old_name='destino',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='newtrip',
            old_name='distancia',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='newtrip',
            old_name='posicion',
            new_name='origen',
        ),
        migrations.RemoveField(
            model_name='newtrip',
            name='tiempo_estimado',
        ),
    ]
