# Generated by Django 5.0.6 on 2024-08-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0015_rename_trailer_newtrip_carro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtrip',
            old_name='order',
            new_name='orden',
        ),
    ]
