import pyautogui
import time
import sys

n = int(sys.argv[1])

time.sleep(3)

for _ in range(n):
    pyautogui.press("enter")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("n")
    pyautogui.press("l")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("1")
    pyautogui.press("2")
    pyautogui.press("0")
    pyautogui.press("5")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("down")
    pyautogui.press("tab")
    pyautogui.press("down")
    pyautogui.press("tab")
    pyautogui.press("down")
    pyautogui.press("tab")
    pyautogui.press("down")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("Enter")
    pyautogui.keyDown("shift")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.keyUp("shift")
    pyautogui.press("t")
    pyautogui.press("p")
    pyautogui.press("2")
    pyautogui.press("tab")
    pyautogui.press("l")
    pyautogui.press("a")
    pyautogui.press("r")
    pyautogui.press("e")
    pyautogui.press("d")
    pyautogui.press("o")
    pyautogui.press("tab")
    pyautogui.press("enter")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")                                          
    pyautogui.press("tab")
    pyautogui.press("enter")
    pyautogui.press("enter")